'use client'
import { CustomProvider } from '@/store/provider'
import './globals.css'
import { Montserrat } from 'next/font/google'
import { Carrito } from '@/components/Carrito'
import { ThemeProvider } from "@material-tailwind/react";
import Example from '@/components/ui/Navbar'
const font = Montserrat({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={font.className}>
      <CustomProvider>
        <ThemeProvider>
          <body className='bg-gray-100'>
            <Example />
            <Carrito/>
            <main className='px-10 py-10'>
              {children}
            </main>
          </body>
        </ThemeProvider>
      </CustomProvider>
    </html>
  )
}
